export const SIGN_IN_INIT = 'SIGN_IN_INIT'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const GET_DEVICE_STATUS_INIT = 'GET_DEVICE_STATUS_INIT'
export const GET_DEVICE_STATUS_SUCCESS = 'GET_DEVICE_STATUS_SUCCESS'
export const GET_DEVICE_STATUS_FAILURE = 'GET_DEVICE_STATUS_FAILURE'

export const TURN_LIGHTS_ON_INIT = 'TURN_LIGHTS_ON_INIT'
export const TURN_LIGHTS_ON_SUCCESS = 'TURN_LIGHTS_ON_SUCCESS'
export const TURN_LIGHTS_ON_FAILURE = 'TURN_LIGHTS_ON_FAILURE'

export const TURN_LIGHTS_OFF_INIT = 'TURN_LIGHTS_OFF_INIT'
export const TURN_LIGHTS_OFF_SUCCESS = 'TURN_LIGHTS_OFF_SUCCESS'
export const TURN_LIGHTS_OFF_FAILURE = 'TURN_LIGHTS_OFF_FAILURE'

